### ISSUE TITLE
关于预制widget，创建快捷方式

### ISSUE THREAD

**Issue by Yukime** [sunboy4103/Launcher3#1]
很高兴可以你的代码，从中我遇到了几个问题，就是不能创建快捷方式，和预制widget，向您请教一下，能否指导我，已star，已fork

**Comment by FightingLarry** [comment]
你说的创建快捷方式和预制Widget是说的在res/xml/default_workspace_5x4.xml上配置的内容吧。
```  
 <appwidget
        launcher:packageName="com.android.settings"
        launcher:className="com.android.settings.widget.SettingsAppWidgetProvider"
        launcher:screen="1"
        launcher:x="0"
        launcher:y="3"
        launcher:spanX="4"
        launcher:spanY="1" />

   <shortcut
        launcher:icon="@drawable/widget_allapps"
        launcher:screen="2"
        launcher:title="@string/apps_navigate"
        launcher:uri="#Intent;action=com.android.launcher3.search.apps.navigate;end"
        launcher:x="0"
        launcher:y="2" />

**Comment by Yalun-Yong** [comment]
恩恩，是的，但是有个问题，就是我写的widget不能在桌面初始化的时候显示，只能兄widget列表中拖出来显示。还有，最近再看您的app分类，感觉不是很能看懂，望指点。。。

**Comment by FightingLarry** [comment]
在default_workspace.xml写了也不行吗？
1、default_workspace.xml这个xml上写，是程序一开始启动才有效的。比如清除数据，如果要做到动态添加，需要写代码。
2、widget一开始显示，需要权限

**Comment by Yalun-Yong** [comment]
恩，default_workspace.xml配置了，也不显示。权限？需要什么权限？

**Comment by FightingLarry** [comment]
<uses-permission android:name="android.permission.BIND_APPWIDGET" />

你可以先widget上拖拽出一个Widget来，如果弹出权限框则，勾选以后默认就行；如果可以显示，说明不是权限问题，可能是你的default_workspace.xml写的不对，default_workspace.xml有很多个，根据手机分辨率不同调用不同的default_workspace.xml。

**Comment by Yalun-Yong** [comment]
恩恩，我试试，大神，我本人经常看你的gethub，也从中学到了不少东西，特别想跟你交流交流，可以的话，加我QQ893417690，谢谢！

**Comment by FightingLarry** [comment]
可以加讨论群，里面都是开发Launcher的大牛。469624689，暗号，Launcher程序猿

**Comment by Yalun-Yong** [comment]
恩恩，好的，谢谢大神！我还是想加你为好友，没有py交易，//坏笑     ///纯属崇拜您的技术
